### ISSUE TITLE
test suite failing on Node.js 8 / 10 / 11

### ISSUE THREAD

**Issue by MylesBorins** [nearform/node-clinic-flame#55] opened 2018-11-29 06:06 UTC
Had to skip it from CITGM test suite

**Comment by goto-bus-stop** [comment] 2018-11-29 10:33
I'd assume that is the cause yes. our CI was also failing for a while and is green since #53 was merged so it should be fine again.

**Comment by MylesBorins** [comment] 2018-11-29 14:55
Please lmk once a new release is out and we can revert the skip on CITGM

**Closed** 2020-02-24 11:47 UTC
